<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Hatifect.Flow</AssemblyName>
    <RootNamespace>Hatifect.Flow</RootNamespace>
    <EnableModDeploy Condition="'$(EnableModDeploy)' == ''">false</EnableModDeploy>
    <EnableModZip>false</EnableModZip>
    <EnableGameDebugging>false</EnableGameDebugging>
    <ModFolderName>Hatifect Flow</ModFolderName>
    <HatifectInstallRelativePath>Hatifect Flow</HatifectInstallRelativePath>
    <Version>3.0.0-rc.89</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.3.2" />
    <ProjectReference Include="Hatifect.Flow.Core/Hatifect.Flow.Core.csproj" />
    <ProjectReference Include="Hatifect.Flow.Persistence/Hatifect.Flow.Persistence.csproj" />
    <ProjectReference Include="Hatifect.Flow.UI.Semantic/Hatifect.Flow.UI.Semantic.csproj" />
    <ProjectReference Include="../Hatifect UI/Hatifect.UI.Experience/Hatifect.UI.Experience.csproj" />
  </ItemGroup>

  <Target Name="CollectFlowRuntime" BeforeTargets="DeployHatifectModule">
    <ItemGroup>
      <HatifectRuntimeFile Include="$(TargetDir)Hatifect.Flow.Core.dll" />
      <HatifectRuntimeFile Include="$(TargetDir)Hatifect.Flow.Persistence.dll" />
      <HatifectRuntimeFile Include="$(TargetDir)Hatifect.Flow.UI.Semantic.dll" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <Compile Remove="Hatifect.Flow.Core/**/*.cs" />
    <Compile Remove="Hatifect.Flow.Persistence/**/*.cs" />
    <Compile Remove="Hatifect.Flow.UI.Semantic/**/*.cs" />
    <Compile Remove="tests/**/*.cs" />
    <InternalsVisibleTo Include="Hatifect.Flow.Stardew.Tests" />
  </ItemGroup>
  <Import Project="../Hatifect.Build.targets" Condition="Exists('../Hatifect.Build.targets')" />
</Project>
